// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'dart:convert';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:http/http.dart';

sendNotification(String title, String body) async {
  final notification = {
    "to": "/topics/pushNotifications",
    "notification": {"title": "$title", "body": "$body", "sound": "default"}
  };
  final headers = {
    'Content-Type': 'application/json',
    'Authorization':
        'key=AAAAKjoHvNc:APA91bGHI65R_cvPo6xNWuF17U71TBZzfDZraN0tUu709-QIbKvdEBANSzmPnjtKQYjAJFbWTzClB5B2juV_9B92_-gasn26jqWjo6qQ3RIXFC8OhC98jawAfVOrTbZYce2BgcXwKVbS'
  };

  await post(Uri.parse("https://fcm.googleapis.com/fcm/send"),
      body: jsonEncode(notification),
      headers: headers,
      encoding: Encoding.getByName('utf-8'));
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7JqZI0jxJYqxfGTQjPtUEkafvhthtQk',
    appId: '1:181362212055:android:a2020c76a1b41bcbe88492',
    messagingSenderId: '181362212055',
    projectId: 'smartcity-85f89',
    databaseURL: 'https://smartcity-85f89-default-rtdb.firebaseio.com',
    storageBucket: 'smartcity-85f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_aXUP6QNcq6ZiITPsdjKj5le6fV85LJ0',
    appId: '1:181362212055:ios:21c6565c11b32ef9e88492',
    messagingSenderId: '181362212055',
    projectId: 'smartcity-85f89',
    databaseURL: 'https://smartcity-85f89-default-rtdb.firebaseio.com',
    storageBucket: 'smartcity-85f89.appspot.com',
    iosClientId:
        '181362212055-jc46f59h7mducnhehhu99n99s4puihs8.apps.googleusercontent.com',
    iosBundleId: 'com.smartcity.app',
  );
}
